### ISSUE TITLE
Zipalign can't be found, can't compress APK!

### ISSUE THREAD

**Issue by XMVZ** [ScRiPt1337/Teardroid-phprat#12]
[+] Compiling Teardroid completed!
[+] Compressing APK Files using zipalign!
'C:\Users\Administrator\Downloads\Teardroid-phprat-master\Teardroid-phprat-master/zipalign' is not recognized as an internal or external command,
operable program or batch file.
[+] Signing Teardroid!
'C:\Users\Administrator\Downloads\Teardroid-phprat-master\Teardroid-phprat-master/apksigner' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Teardroid-phprat-master\Teardroid-phprat-master\Teardroid.py", line 72, in <module>
    builder(args.build)
  File "C:\Users\Administrator\Downloads\Teardroid-phprat-master\Teardroid-phprat-master\Teardroid.py", line 61, in builder
    Teardroid.Clear()
  File "C:\Users\Administrator\Downloads\Teardroid-phprat-master\Teardroid-phprat-master\Builder.py", line 62, in Clear
    os.remove(self.name + ".apk.idsig")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Kylies_Secrets.apk.idsig'

**Comment by XMVZ** [comment]
Switched to GIT Bash and got this:

[+] Changing app name to Kylieee!
[+] Changing app name completed!
[+] Changing notification title to Kylie!
[+] Changing notification content to Secrets!
[+] Changing notification subtext to Nudes!
[+] Changing notification completed!
[+] Compiling Teardroid using apktool!
[+] Compiling Teardroid completed!
[+] Compressing APK Files using zipalign!
[+] Signing Teardroid!
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Teardroid-phprat-master\Teardroid-phprat-master\Teardroid-phprat\Teardroid.py", line 72, in <module>
    builder(args.build)
  File "C:\Users\Administrator\Downloads\Teardroid-phprat-master\Teardroid-phprat-master\Teardroid-phprat\Teardroid.py", line 61, in builder
    Teardroid.Clear()
  File "C:\Users\Administrator\Downloads\Teardroid-phprat-master\Teardroid-phprat-master\Teardroid-phprat\Builder.py", line 62, in Clear
    os.remove(self.name + ".apk.idsig")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Kylieee.apk.idsig'

**Comment by ScRiPt1337** [comment]
please share a screenshot of the error and also a screenshot with ls command

**Comment by ScRiPt1337** [comment]
And please try it on a Linux distro

**Comment by XMVZ** [comment]
This is on Linux distro:

root@localhost:~/Teardroid-phprat# python Teardroid.py
  File "Teardroid.py", line 18
    apktool: str = os.getcwd() + "/apktool.sh"
           ^
SyntaxError: invalid syntax
root@localhost:~/Teardroid-phprat# ls
apksigner    apktool.sh  CODE_OF_CONDUCT.md  img  lib64    README.md         Teardroid_Payload  zipalign
apktool.jar  Builder.py  hacksec.jks         lib  LICENSE  requirements.txt  Teardroid.py
root@localhost:~/Teardroid-phprat# python Teardroid.py -b Kylieee
  File "Teardroid.py", line 18
    apktool: str = os.getcwd() + "/apktool.sh"
           ^
SyntaxError: invalid syntax
root@localhost:~/Teardroid-phprat#

**Comment by XMVZ** [comment]
@ScRiPt1337 I'm not sure why it is crossing out with lines above! But yeah, have followed all steps, no OS supports it seems...

**Comment by XMVZ** [comment]
[
![Screenshot 2022-01-29 043818](https://user-images.githubusercontent.com/79497004/151661345-3d8282c5-0110-4c41-96c3-d0b83751a3cb.png)
](url)

**Comment by XMVZ** [comment]
And APKTOOL is installed.

**Comment by ScRiPt1337** [comment]
which version of python your using

**Comment by XMVZ** [comment]
I installed 3 via CLI but it looks like it's running:

root@localhost:~/Teardroid-phprat# python --version
Python 2.7.18
root@localhost:~/Teardroid-phprat# 

Gonna take a guess and assume that's why?

**Comment by ScRiPt1337** [comment]
yes, use python 3 because python 2 does not support python3  Syntex try python 3.10

**Comment by XMVZ** [comment]
it's not letting me install python 3...
how do I install python 3 on Ubuntu ?

**Comment by ScRiPt1337** [comment]
sudo apt-get install python3

**Comment by XMVZ** [comment]
![image](https://user-images.githubusercontent.com/79497004/151661958-093d723c-d784-449c-ae5c-4ec6ed572858.png)

**Comment by XMVZ** [comment]
I tried that, but it still uses 2.7... How do I override that and use 3?

**Comment by XMVZ** [comment]
root@localhost:~/Teardroid-phprat# sudo apt-get install python3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3 is already the newest version (3.9.4-1build1).
python3 set to manually installed.
The following packages were automatically installed and are no longer required:
  libjemalloc2 liblua5.1-0 liblzf1 lua-bitop lua-cjson
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@localhost:~/Teardroid-phprat#

**Comment by XMVZ** [comment]
Ah, I just have to use Python3 command I guess... Let's see if that doesnt toss any syntax errors..

**Comment by ScRiPt1337** [comment]
> Ah, I just have to use Python3 command I guess... Let's see if that doesnt toss any syntax errors..

yes

**Comment by XMVZ** [comment]
@ScRiPt1337 I was able to make the build.
When I open the app, it prompts about everything (can this app access SMS, APPS, etc..) is there a way to avoid that? 
But past that, I don't receive a connection on my panel...

What do  I do?

**Comment by ScRiPt1337** [comment]
please create a video about the hole process how your building it and share it here and sorry you have to give permission I cant bypass it for now

**Comment by ScRiPt1337** [comment]
make sure you enter the host URL without / at the end 
example: https://teardroid.deta.dev (CORRECT)
https://teardroid.deta.dev/ (WRONG)

**Comment by ScRiPt1337** [comment]
I think it's fixed now
