### ISSUE TITLE
Error zipalign

### ISSUE THREAD

**Issue by hakai45** [ScRiPt1337/Teardroid-phprat#13]
error while signning with zipalign i have screenshot 
Here
![Screenshot_20220210-130118_NetHunter KeX](https://user-images.githubusercontent.com/72738456/153359278-34cfbf59-37a1-4e18-980e-91d5cd044951.jpg)
Plzzz help

**Comment by ScRiPt1337** [comment]
show me all files inside the teardroid folder

**Comment by hakai45** [comment]
I have fixed it just to change the folder of zipalign

**Comment by hakai45** [comment]
![Uploading Screenshot_20220211-164106_NetHunter KeX.jpg…]()

**Comment by ScRiPt1337** [comment]
Your screenshot is not visible

**Comment by hakai45** [comment]
![Uploading Screenshot_20220211-164106_NetHunter KeX.jpg…]()

**Comment by hakai45** [comment]
![Uploading Screenshot_20220211-164106_NetHunter KeX.jpg…]

**Comment by ScRiPt1337** [comment]
Why you reopen this issue are still facing the same problem

**Comment by hakai45** [comment]
Yup bro

**Comment by hakai45** [comment]
![Screenshot_20220211-182220_NetHunter KeX](https://user-images.githubusercontent.com/72738456/153600306-221ef267-d79a-4286-87fd-add59120f5ac.jpg)

**Comment by ScRiPt1337** [comment]
Send me the error screenshot

**Comment by hakai45** [comment]
Already sended

**Comment by hakai45** [comment]
![Uploading Screenshot_20220210-130118_NetHunter KeX.jpg…]()

**Comment by hakai45** [comment]
![Screenshot_20220210-130118_NetHunter KeX](https://user-images.githubusercontent.com/72738456/153602275-81e75e75-4ede-47f2-8c45-2e7013bef1dd.jpg)

**Comment by ScRiPt1337** [comment]
I am not able to reproduce this bug

**Comment by hakai45** [comment]
Then now how to do it bro

**Comment by ScRiPt1337** [comment]
Send me a video

**Comment by hakai45** [comment]
https://youtu.be/Ii9YYVxRXRI

**Comment by Monodeepdeb** [comment]
I too am suffering from the same issue...
And was unable to fix it from the solution given in issue #12

**Comment by hakai45** [comment]
https://youtu.be/Ii9YYVxRXRI

**Comment by hakai45** [comment]
https://youtu.be/Ii9YYVxRXRI

**Comment by hakai45** [comment]
Sorry by mistake sendend same link

**Comment by hakai45** [comment]
i am already using python3

**Comment by ScRiPt1337** [comment]
Are you using 64 bit os

**Comment by hakai45** [comment]
Yes aarch64

**Comment by ScRiPt1337** [comment]
how your running kali on android

**Comment by hakai45** [comment]
Kali givs us permission

**Comment by hakai45** [comment]
Gived code offically to download and run in termux

**Comment by hakai45** [comment]
non root android but give power of root in kali

**Comment by ScRiPt1337** [comment]
Use a real pc to build this apktool tool giving us error when we try to recompile it on android.
