### ISSUE TITLE
Can´t change icon

### ISSUE THREAD

**Issue by ZOE12123** [ScRiPt1337/Teardroid-phprat#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ScRiPt1337** [comment]
> The icon change is impossible .... i change ic_launcher from mipmap folders all and folder an multiples ways routes for and multiple extensions .jpeg .png .webp and all resizes for all px and all forms not working, help me please , thanks

Compile it with android-studio  changing the icon is decompiled apk not working
