### ISSUE TITLE
Getting Error While Building Apk

### ISSUE THREAD

**Issue by TrackyMayank** [ScRiPt1337/Teardroid-phprat#15]
Sir, I'm getting error while Building apk, I'm using Kali Linux on Raspberry pi 4b. Thankyou 
![image](https://user-images.githubusercontent.com/94278423/153570207-7717a981-9eb2-4eda-b2d4-346c6d7f9187.png)

**Comment by ScRiPt1337** [comment]
Can you send the entire output screenshot

**Comment by ScRiPt1337** [comment]
And tour os arch information

**Comment by ScRiPt1337** [comment]
i think its fixed

**Comment by vokica** [comment]
the problem is use sudo!

**Comment by vokica** [comment]
> Sir, I'm getting error while Building apk, I'm using Kali Linux on Raspberry pi 4b. Thankyou ![image](https://user-images.githubusercontent.com/94278423/153570207-7717a981-9eb2-4eda-b2d4-346c6d7f9187.png)

USE SUDO

**Comment by Het-Joshi** [comment]
![image](https://github.com/ScRiPt1337/Teardroid-phprat/assets/96608251/5b97b284-0cae-45a9-8ce5-d4e06efd3cfa)
 I have the same issue.
 Used sudo aswell
OS : KDE Neon (Debian based)

**Comment by ScRiPt1337** [comment]
> ![image](https://user-images.githubusercontent.com/96608251/250342878-5b97b284-0cae-45a9-8ce5-d4e06efd3cfa.png)
> I have the same issue.
> Used sudo aswell
> OS : KDE Neon (Debian based)

you dont have java installed or java in not in path

**Comment by Het-Joshi** [comment]
Alright that fixed it :D
