### ISSUE TITLE
Getting Error While Building Apk 

### ISSUE THREAD

**Issue by TrackyMayank** [ScRiPt1337/Teardroid-phprat#16]
Sir, I'm getting error while Building apk, I'm using Kali Linux on Raspberry pi 4b. Thankyou 
![Screenshot_20220213-114810447](https://user-images.githubusercontent.com/94278423/153741454-06f9e091-4e6e-48ec-8a7d-1b2d3df173c3.jpg)
![Screenshot_20220213-103814116](https://user-images.githubusercontent.com/94278423/153741459-edf080dd-77ff-4203-a8c1-45dbea884100.jpg)

**Comment by Rocky8088** [comment]
I'm facing dashboard login problem

**Comment by TrackyMayank** [comment]
> 

Bro i think i know solution of your problem 😁,
Just use small letter like this :- admin admin

**Comment by Rocky8088** [comment]
Password did not conform with policy: Password must have uppercase characters

**Comment by ScRiPt1337** [comment]
> Password did not conform with policy: Password must have uppercase characters

we don't have any policy like this login form

**Comment by ScRiPt1337** [comment]
> Sir, I'm getting error while Building apk, I'm using Kali Linux on Raspberry pi 4b. Thankyou ![Screenshot_20220213-114810447](https://user-images.githubusercontent.com/94278423/153741454-06f9e091-4e6e-48ec-8a7d-1b2d3df173c3.jpg) ![Screenshot_20220213-103814116](https://user-images.githubusercontent.com/94278423/153741459-edf080dd-77ff-4203-a8c1-45dbea884100.jpg)

use an computer  to compile it
