### ISSUE TITLE
Using Own VPS instead

### ISSUE THREAD

**Issue by tehseensagar** [ScRiPt1337/Teardroid-phprat#19]
Project is awesome , I wonder if I could use my own vps instead of using data . If there is any way please guide me.

Regards

**Comment by ScRiPt1337** [comment]
yes you can use uvicorn and gunicorn

**Comment by tehseensagar** [comment]
can you please explain a bit ? I would appriciate if you can guide to deploy it on my local machine / vps with out using deta.
