### ISSUE TITLE
where's compiled apk ?

### ISSUE THREAD

**Issue by fdciabdul** [ScRiPt1337/Teardroid-phprat#2]
i need compiled apk for this , because i got an error when build with gradle

**Comment by graysuit** [comment]
@fdciabdul 
https://github.com/graysuit/Teardroid-phprat/actions/runs/583688523

**Comment by fdciabdul** [comment]
> @fdciabdul
> https://github.com/graysuit/Teardroid-phprat/actions/runs/583688523

where bro ?

**Comment by graysuit** [comment]
@fdciabdul 
Click the **app** link at left-bottom.

![Capture](https://user-images.githubusercontent.com/54432616/108596191-46d38f00-73a5-11eb-9eba-5083bdaa0aba.PNG)

Here direct link as well:
http://github.com/graysuit/Teardroid-phprat/suites/2083211073/artifacts/42208190

But remember its un-signed and un-zip aligned.
You need to do following settings as well:
- Fork it and change control panel server link . It would automatically build apk.
- after, sign the apk and then zipalign apk.

**Comment by fdciabdul** [comment]
> @fdciabdul
> Click the **app** link at left-bottom.
> 
> ![Capture](https://user-images.githubusercontent.com/54432616/108596191-46d38f00-73a5-11eb-9eba-5083bdaa0aba.PNG)
> 
> Here direct link as well:
> [http://github.com/graysuit/Teardroid-phprat/suites/2083211073/artifacts/42208190](https://github.com/graysuit/Teardroid-phprat/suites/2083211073/artifacts/42208190)
> 
> But remember its un-signed and un-zip aligned.
> You need to do following settings as well:
> 
> * Fork it and change control panel server link . It would automatically build apk.
> * after, sign the apk and then zipalign apk.

that's broken app ? bc i can't open it

**Comment by graysuit** [comment]
@fdciabdul 
Join there, I would discuss more betterly there:
https://discord.com/invite/Hu5XPGMTuk

**Comment by ScRiPt1337** [comment]
Please post your error log

**Comment by urgheuigrpauipeg** [comment]
> @fdciabdul
> Please post your error log

He probably just had a bad build environment.

**Comment by ScRiPt1337** [comment]
Yes
