### ISSUE TITLE
any help with standalone setup with webpanel

### ISSUE THREAD

**Issue by tehseensagar** [ScRiPt1337/Teardroid-phprat#20]
https://github.com/ScRiPt1337/Teardroid-phprat/issues/19)](https://github.com/ScRiPt1337/Teardroid-phprat/issues/19
Thanks for your prompt response.

but could you please guide or explain to deploy it standalone on local / vps.

**Comment by ScRiPt1337** [comment]
we still dont have any guide for this so maybe if future we will publish a guide

**Comment by tehseensagar** [comment]
Well Hope to hear it from you soon
