### ISSUE TITLE
App crash on ANDROID 12 BASED aosp

### ISSUE THREAD

**Issue by unnbreak** [ScRiPt1337/Teardroid-phprat#21]
App crashes after giving all permissions

**To Reproduce**
1. Install the app after building
2. Grant all passion
3. App crashes and unable to load again

**Expected behavior**
App opening and new client notification on dashboard

Not even being added on dashboard

**Comment by ScRiPt1337** [comment]
Please create a video and send me here

**Comment by ScRiPt1337** [comment]
i thing this issue is fix reopen it if you face the ask issue again
