### ISSUE TITLE
builder 

### ISSUE THREAD

**Issue by anwarzidan63** [ScRiPt1337/Teardroid-phprat#24]
![Screenshot_2022-03-13-04-17-15-929_com offsec nhterm](https://user-images.githubusercontent.com/75133429/158042040-4dcf85ca-ea87-4f27-ac51-b6e9d010d1bd.jpg)
how i can fix?
run in kali nethunter

**Comment by yaassoo** [comment]
replace file apktool.jar With this file you will find in Mega But when you build, you will find an error sign  To solve it, download mt manager And carry out an order sign Or you can search for a replacement zipali with a new file

**Comment by anwarzidan63** [comment]
i replace apktool.jar and the same error when building apk

**Comment by ScRiPt1337** [comment]
> i replace apktool.jar and the same error when building apk

We don't support android device use an vps or rdp to compile the apk

**Comment by anwarzidan63** [comment]
ok i have kali Linux in virtualbox i will test that

**Comment by ScRiPt1337** [comment]
okay
