### ISSUE TITLE
Error builder

### ISSUE THREAD

**Issue by lucthienphong1120** [ScRiPt1337/Teardroid-phprat#25]
![image](https://user-images.githubusercontent.com/90561566/158374580-b27051aa-a39c-4e29-833e-65a94df60905.png)
help me! i can't build the apk

**Comment by ScRiPt1337** [comment]
try a linux system until i fix it and please create a zip of your teardroid-phprat folder and send it here

**Comment by lucthienphong1120** [comment]
okay thanks
