### ISSUE TITLE
ADD WEB VIEW IN APP HOME SCREEN BLACK SCREEN NOT LIKEY

### ISSUE THREAD

**Issue by fxflash** [ScRiPt1337/Teardroid-phprat#27]
PLSS ADD WEB VIEW IN APP BLACK SCREEN NOT LIKELY

*IF POSSIBLE THEN ADD IF VICTIM GIVE ACCESSBILILTY PERMISSION THEN ALL PERMISSION AUTO ALLOW AND APP ANTI DELETE 😀

**Comment by ScRiPt1337** [comment]
Okay i will think about it
