### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by umarahmad125** [ScRiPt1337/Teardroid-phprat#29]
Error
![Uploading Screenshot_20220328-045429_2.jpg…]()

**Comment by umarahmad125** [comment]
![Screenshot_20220328-045429_2](https://user-images.githubusercontent.com/47673584/160306781-89b29d72-6321-4b6a-a320-f1fec4aca348.jpg)

**Comment by ScRiPt1337** [comment]
we does not support android read the readme.md file to know our supported system
