### ISSUE TITLE
Devices not showing up

### ISSUE THREAD

**Issue by BotAndis** [ScRiPt1337/Teardroid-phprat#34]
A popup shows on the device, but no virtual machine or physical phone is showing up in the control panel. I tried many different versions of the link, but none made a difference.

Followed all steps and used the Deployment button (not manual installation).

Windows 10
Python Version : 3.10
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
"jdk-8u333-windows-x64.exe" is installed

Log output(always the same):

Visor request (headers):
{
    "Accept": "application/json, text/plain, */*",
    "Connection": "close",
    "Referer": "https://[replaced].deta.dev/v4/overview",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
    "X-Forwarded-Proto": "https",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Site": "same-origin",
    "Host": "[replaced].deta.dev",
    "Accept-Encoding": "gzip, deflate, br",
    "X-Forwarded-Port": "443",
    "Sec-Fetch-Mode": "cors",
    "Sec-Gpc": "1",
    "X-Forwarded-For": "99.82.163.58",
    "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
    "X-Real-Ip": "99.82.163.58"
}

Visor response:
{
    "success": true,
    "clients": []
}

Logs:
No errors

Visor request (headers):
{
    "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
    "Connection": "close",
    "Referer": "https://[replaced].deta.dev/v4/overview",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
    "X-Forwarded-Proto": "https",
    "Sec-Fetch-Dest": "image",
    "Sec-Fetch-Site": "same-origin",
    "Host": "[replaced].deta.dev",
    "Accept-Encoding": "gzip, deflate, br",
    "X-Forwarded-Port": "443",
    "Sec-Fetch-Mode": "no-cors",
    "Sec-Gpc": "1",
    "X-Forwarded-For": "99.82.163.58",
    "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
    "X-Real-Ip": "99.82.163.58"
}

Visor respone:
"<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"/><link rel=\"icon\" href=\"/favicon.ico\"/><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/><meta name=\"theme-color\" content=\"#000000\"/><meta name=\"description\" content=\"Web site created using create-react-app\"/><link rel=\"apple-touch-icon\" href=\"/logo192.png\"/><link rel=\"manifest\" href=\"/manifest.json\"/><link rel=\"stylesheet\" href=\"https://unpkg.com/@shopify/polaris@7.6.0/build/esm/styles.css\"/><title>Teardroid v4.0</title><script defer=\"defer\" src=\"/static/js/main.58405be5.js\"></script><link href=\"/static/css/main.101b48ee.css\" rel=\"stylesheet\"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id=\"root\"></div></body></html>"

Logs:
No errors

**Comment by ScRiPt1337** [comment]
On which android version your trying it and please check if there is any crash log in logcat

**Comment by BotAndis** [comment]
Tried versions from 8 to 11, checked logcat, but could not see anything wrong. Could you elaborate anyway on logcat, maybe I was looking for the wrong thing.

**Comment by BotAndis** [comment]
Is this helpful, or am I stupid and looking at the wrong place:

```
05-06 12:27:29.983  7641  7682 E Volley  : [551] NetworkUtility.shouldRetryException: Unexpected response code 405 for https://[replaced^^].deta.dev/v4/overview/client/add
```
+ some stuff below:
```
05-06 12:27:29.991  7641  7641 D Teardroid: null
05-06 12:27:30.092  1753  1753 W audio_hw_generic: Not supplying enough data to HAL, expected position 3693520 , only wrote 3556180
05-06 12:27:30.248  1753  6963 W audio_hw_generic: Not supplying enough data to HAL, expected position 3556199 , only wrote 3556180
05-06 12:27:30.266  2362  6149 I Icing   : Indexing done com.google.android.gms-apps
05-06 12:27:30.367  1778  1869 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5496832
05-06 12:27:30.385  1778  1869 I chatty  : uid=1000(system) HwBinder:1778_2 identical 1 line
05-06 12:27:30.389  1778  1869 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 5496832
05-06 12:27:30.406  7667  7697 D EGL_emulation: eglMakeCurrent: 0xdc92f340: ver 2 0 (tinfo 0xc53b4240)
05-06 12:27:30.433  7667  7697 I chatty  : uid=1000(system) RenderThread identical 2 lines
05-06 12:27:30.454  7667  7697 D EGL_emulation: eglMakeCurrent: 0xdc92f340: ver 2 0 (tinfo 0xc53b4240)
05-06 12:27:30.458  2184  2454 D EGL_emulation: eglMakeCurrent: 0xe7f10c40: ver 2 0 (tinfo 0xc797b420)
05-06 12:27:31.317  2014  2043 I RoleUserState: Wrote roles.xml successfully
05-06 12:27:30.624  2184  2454 I chatty  : uid=10114(com.android.systemui) RenderThread identical 10 lines
05-06 12:27:30.632  2184  2454 D EGL_emulation: eglMakeCurrent: 0xe7f10c40: ver 2 0 (tinfo 0xc797b420)
05-06 12:27:31.485  7667  7697 D EGL_emulation: eglMakeCurrent: 0xdc92f340: ver 2 0 (tinfo 0xc53b4240)
05-06 12:27:31.488  2014  2877 I ConditionProviders:  Allowing condition provider com.example.teardroidv2/com.example.teardroidv2.NotificationListenerService
05-06 12:27:31.488  2014  2877 I NotificationListeners:  Allowing notification listener com.example.teardroidv2/com.example.teardroidv2.NotificationListenerService
05-06 12:27:31.489  2014  2877 V NotificationListeners: enabling notification listener for 0: ComponentInfo{com.example.teardroidv2/com.example.teardroidv2.NotificationListenerService}
05-06 12:27:31.492  2014  2877 V NotificationListeners: binding: Intent { act=android.service.notification.NotificationListenerService cmp=com.example.teardroidv2/.NotificationListenerService (has extras) }
05-06 12:27:31.495  2014  2877 V NotificationListeners: enabling notification listener for 0: ComponentInfo{com.google.android.apps.nexuslauncher/com.android.launcher3.notification.NotificationListener}
05-06 12:27:31.495  2014  2877 V NotificationListeners: Not registering ComponentInfo{com.google.android.apps.nexuslauncher/com.android.launcher3.notification.NotificationListener} is already bound
05-06 12:27:31.499  2014  2014 V SettingsProvider: Notifying for 0: content://settings/secure/enabled_notification_listeners
05-06 12:27:31.502  2014  2014 V NotificationListeners: 0 notification listener service connected: ComponentInfo{com.example.teardroidv2/com.example.teardroidv2.NotificationListenerService}
```

**Comment by ScRiPt1337** [comment]
remove /v4/overview/  from the control panel URL when building the app

**Comment by BotAndis** [comment]
ok but I tried that already

**Comment by BotAndis** [comment]
Alright thanks
Got it working, not sure if it really was the URL, if yes then I feel really stupid, because I literally tried every option, maybe I did I forgot to try one apk or something like that c:
Thanks!
