### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by realartin** [ScRiPt1337/Teardroid-phprat#36]
hi i tried to run your script on my ubuntu server using python 3.10 this is what happen ?
please help me 

root@srv190297:~/rat/Teardroid-phprat# pip install -r requirements.txt
Requirement already satisfied: pyfiglet in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (0.8.post1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (4.64.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (1.9.1)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (0.4.3)
Requirement already satisfied: emoji in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (1.7.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from pydantic->-r requirements.txt (line 3)) (4.2.0)
root@srv190297:~/rat/Teardroid-phprat# python3.10 Teardroid.py
Traceback (most recent call last):
  File "/root/rat/Teardroid-phprat/Teardroid.py", line 7, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'
root@srv190297:~/rat/Teardroid-phprat#

**Comment by ScRiPt1337** [comment]
type pip install pyfiglet
