### ISSUE TITLE
Deta.sh is banning this...plz.resolve

### ISSUE THREAD

**Issue by mahim66** [ScRiPt1337/Teardroid-phprat#39]

**Comment by ScRiPt1337** [comment]
Please deploy it manually

**Comment by mahim66** [comment]
> Please deploy it manually

Deployed... Manually on deta...same issue

**Comment by ScRiPt1337** [comment]
> > Please deploy it manually
> 
> Deployed... Manually on deta...same issue

I have just check and its working without any banning issue 
Run deta deploy command from inside the  teardroid_control folder

**Comment by seraohzero86** [comment]
I am getting this issue with 404 error page and this came up , any ideas ?
// deta deploy
Error: failed to get details: Micro ddb1a250-da3e-4c8d-9d8a-48b4db8eac90 not found

**Comment by krisdowis** [comment]
> I am getting this issue with 404 error page and this came up , any ideas ? // deta deploy Error: failed to get details: Micro ddb1a250-da3e-4c8d-9d8a-48b4db8eac90 not found tried to create a new one but it says its present . Solution , delete eveything on the control folder. Create a new micro and it will start running again .

i am having same issue

**Comment by ScRiPt1337** [comment]
> > I am getting this issue with 404 error page and this came up , any ideas ? // deta deploy Error: failed to get details: Micro ddb1a250-da3e-4c8d-9d8a-48b4db8eac90 not found tried to create a new one but it says its present . Solution , delete eveything on the control folder. Create a new micro and it will start running again .
> 
> i am having same issue

deploy it on your own vps will be the best option
