### ISSUE TITLE
Teardroid.py can't start show this error 

### ISSUE THREAD

**Issue by as9931415** [ScRiPt1337/Teardroid-phprat#40]
$ python Teardroid.py
[+] Checking Python Version
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Soft Source\New folder\Teardroid-phprat\Teardroid.py", line 29, in <module>
    if check_python() == False:
  File "C:\Users\User\Desktop\Soft Source\New folder\Teardroid-phprat\Teardroid.py", line 22, in check_python
    print("[+] Python Version : " +
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 26: character maps to <undefined>

------------------------------------------------------------------------------------------------------------------------------------------------

User@DESKTOP-VJUGN4Q MINGW64 ~/Desktop/Soft Source/New folder/Teardroid-phprat (master)
$ java -version
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

User@DESKTOP-VJUGN4Q MINGW64 ~/Desktop/Soft Source/New folder/Teardroid-phprat (master)
$ python --version
Python 3.10.5

**Comment by ScRiPt1337** [comment]
your codec does not support emoji I guess try it on tested os I have mentioned in the readme.md
