### ISSUE TITLE
Change App ICON

### ISSUE THREAD

**Issue by motikolorado** [ScRiPt1337/Teardroid-phprat#48]
Please Enable App Icon and Splash screen for startup unless. Its useless because nobody will keep an app that shows blank screen on thier phone. Make the App do something at least, even if its just a splash screen so they wait and give up but they might not uninstall the app If you convince them that it takes time to load up. They will just give up but wait to try another time like one hunting game i downloaded earlier... it just stays on the splash screen loading... probably a gif decoy.

Make it possible to upload a gif splash screen so the victims see loading...

**Comment by ScRiPt1337** [comment]
this version of teardroid is just a demo

**Comment by ScRiPt1337** [comment]
it has been added
