### ISSUE TITLE
Error: no deta micro initilialized, see `deta new --help` to create a micro

### ISSUE THREAD

**Issue by rustyslash** [ScRiPt1337/Teardroid-phprat#51]
![image](https://user-images.githubusercontent.com/107748673/195165281-30874f48-0f4f-4113-af7f-545caea42b6f.png)
![image](https://user-images.githubusercontent.com/107748673/195165483-65356413-6bbb-44bc-bd2a-8fc341bf2ea4.png)

really?:/

**Comment by timmywag2** [comment]
its deta's fault fr

**Comment by ScRiPt1337** [comment]
You forget to create the deta micro first before deploying

**Comment by jerbear2008** [comment]
Don't worry, deta is actively working on banning this app from their service.

**Comment by ScRiPt1337** [comment]
> Don't worry, deta is actively working on banning this app from their service.

lol
