### ISSUE TITLE
Need Video Tutorial To Deploy On Ubuntu

### ISSUE THREAD

**Issue by flashxteam** [ScRiPt1337/Teardroid-phprat#55]
I Many Times Try To Deploy But Facing Error I Try Many Times As  Tutorial. I Seen And Try Many Andriod Rat But I Love it Thanks for Make Please Solve My Issuse I wana deploy on my server but i cant i try on many server ubnuntu,kali,centos still i cant deploy

**Comment by ScRiPt1337** [comment]
copy paste the error your getting

**Comment by ScRiPt1337** [comment]
now days i am really busy i will not be able to do it  but I will mention it on readme.md file if I find any on youtube
