### ISSUE TITLE
how to bypass google protect!!

### ISSUE THREAD

**Issue by bistiks1979** [ScRiPt1337/Teardroid-phprat#56]
ok i create  the apk so what how i will bypass google protect always the same problem i changed sdk but i got error and how i will give access to target device?

**Comment by ScRiPt1337** [comment]
sing the apk with a new key rather then using  the default one

**Comment by bistiks1979** [comment]
generally i hate questions to others :)but how i will sigh with new key ?an second question when i close laptop deta micro dissapear from deta and control panel teardroid v4 says 404 not found how i will reopen them to gain access again please help!

**Comment by ScRiPt1337** [comment]
> generally i hate questions to others :)but how i will sigh with new key ?an second question when i close laptop deta micro dissapear from deta and control panel teardroid v4 says 404 not found how i will reopen them to gain access again endpoint adress wont open please help!

google how you can sign an apk.
and host it on your own server if possible.

**Comment by bistiks1979** [comment]
thanks!!

**Comment by ScRiPt1337** [comment]
> 

how to sign a apk without android studio => google this
, and all the instructions are given in the readme.md file how you can deploy it on your own server

**Comment by bistiks1979** [comment]
thanks i aprecciate your help

**Comment by bistiks1979** [comment]
Logging in to Deta via the CLI  but i cant what i do wrong i am in root terminal i write deta login and says command not found or whatever?

**Comment by ScRiPt1337** [comment]
> 
double check every steps and read the docs maybe your missing something and if its still not fixing the issue then report it to deta.sh

**Comment by bistiks1979** [comment]
Manually add /root/.deta/bin/deta to your path:
  export PATH="/root/.deta/bin:$PATH"  come on man i am not a specialist help me with this error deta Add export PATH="~/.deta/bin:$PATH" in your .bashrc file which you can find in your home directory i dont understand this

**Comment by bistiks1979** [comment]
i found the solution thanks but now i have another problem how i bring back micro adress and have accees in teardroid control panel again ?if i close internet says 404not found

**Comment by bistiks1979** [comment]
i createdin my own server as you said but i enter in control panel i put name and password and nothing says not found what i do wrong ?

**Comment by ScRiPt1337** [comment]
> i createdin my own server as you said but i enter in control panel i put name and password and nothing says not found what i do wrong ?

enter your data project in db/database.py files

**Comment by bistiks1979** [comment]
db/database.py can be found in 2 folders in teardroid_control that is in root mode and teardroidv4_api and what you mean enter my data project you mean the keyand how i will enter my data?

**Comment by ScRiPt1337** [comment]
> db/database.py can be found in 2 folders in teardroid_control that is in root mode and teardroidv4_api and what you mean enter my data project you mean the keyand how i will enter my data?

It can be found inside teardroidv4_api  and I told you to put your Deta.sh accounts project key

**Comment by bistiks1979** [comment]
deta = Deta("a0c1ofq2_ZVzniZBC5G3Z3Kzg5y2R32N..........!i put it yesterday that i was creating it i must do it again manually.and the last question micro  dissapear from deta.sh how i will bring it back?and tell me how can i buy you a coffee please!!

**Comment by ScRiPt1337** [comment]
> deta = Deta("a0c1ofq2_ZVzniZBC5G3Z3Kzg5y2R32N..........!i put it yesterday that i was creating it i must do it again manually.and the last question micro dissapear from deta.sh how i will bring it back?and tell me how can i buy you a coffee please!!

You can’t being it back that’s why we are self hosting

**Comment by bistiks1979** [comment]
Can you send me a video how to do thatvi will pay you if necessary

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ScRiPt1337** [comment]
> Can you send me a video how to do thatvi will pay you if necessary Sent from Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)

Message me on telegram https://t.me/script1337
