### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by kali64amd** [ScRiPt1337/Teardroid-phprat#63]
I'm getting this error ...HTTP Error 401: Unauthorized 
![err2](https://user-images.githubusercontent.com/28497075/235428976-4f1bc89d-8706-4c0b-8ec8-060bd19e4198.png)

![error1](https://user-images.githubusercontent.com/28497075/235428995-3444cb5f-1eb8-48d5-a104-f9d789c3dd4c.png)

**Comment by ScRiPt1337** [comment]
have you deploy it by yourself or using the setup.py

**Comment by kali64amd** [comment]
I have deploy by myself because setup.py is not working....

![setup](https://user-images.githubusercontent.com/28497075/235440510-fc63bbb3-d0ec-4e95-b7cf-43d9cd4cef8b.png)

**Comment by ScRiPt1337** [comment]
i have updated the repo please follow the hole process again using setup.py and lets me know if its solved and make sure delete the old download repo files and download them again and start fresh

**Comment by kali64amd** [comment]
It's working now !!!

Appreciate you'r help!!
