### ISSUE TITLE
Future Enhancements (Suggestion) 

### ISSUE THREAD

**Issue by kali64amd** [ScRiPt1337/Teardroid-phprat#66]
First of all its Awesome RAT so far I have seen in git hub and its work on VPS. if you update these couple of things it will make complete

MAJOR CHANGES

1) Android battery optimization bypass
2) Forground service bypass
3) Should work on Ideal Mod 

MINOR CHANGES

1) Geo location not accurate
2) Shell command not working

**Comment by kali64amd** [comment]
Shell command -----> sysinfo -----------------> Error need root user (Android ver 9)

And I do believe it's a bug when I have reinstall my apk on same device its not showing (online) on control panel, 

If you add offline device on control panel it would be nice! plus Delete device option.

**Comment by ScRiPt1337** [comment]
if you have reinstall the app it should show it as a new device

**Comment by kali64amd** [comment]
I have given all permission in Android and take off google play protect but still no luck.

couple of time reinstall it, still no connected device.

**Comment by ScRiPt1337** [comment]
remove the /v4 from the end of your control panel url

**Comment by kali64amd** [comment]
It's worked !!

**Comment by kali64amd** [comment]
Couple of more suggestions

1) Need to take picture from front and back camera
2) user can record audio upto 1 or 4 minutes (if possible then listen live)
3) user can take Screenshots

**Comment by ScRiPt1337** [comment]
if you want more features try scatter alfa
