### ISSUE TITLE
DETA.SH is banning this! Plz suggest alternatives 

### ISSUE THREAD

**Issue by mahim66** [ScRiPt1337/Teardroid-phprat#67]
Deta.sh is banning this, suggest an alternative free of cost

**Comment by ScRiPt1337** [comment]
please show me how you have deploed it

**Comment by ScRiPt1337** [comment]
can  you please make a video how you have did it because my is not banned yet

**Comment by mahim66** [comment]
Can we connect on telegram mate?

@MR_S0LO

**Comment by ScRiPt1337** [comment]
yes but we should keep you convo related to this issue here so other also can learn and solve there issue related to this

**Comment by mahim66** [comment]
Ok i will let you know here by making video

**Comment by ScRiPt1337** [comment]
okay bro

**Comment by mahim66** [comment]
[image: image.png]

{it will open deta.space on your browser and ask you to click on the search
bar and click on setting then generate access token
copy the access token and paste it in the terminal or cmd
it will setup the panel for you automatically and give you the panel url at
the end when the deployment is done}

could not understand bro! how to do this? when i first time tried your
project ,probably 1 year ago ..then i did this successfully ,after some
days ,control panel was not found (probably deta banned that project)..but
now deta maybe updated their interface ,could not recognize your
instructions ,,plz check it

**Comment by mahim66** [comment]
[image: image.png]

**Comment by mahim66** [comment]
mate ,i successfully build this ....detas interface was changed,nothing
else ....what can i do with shell? you just specified 2 shell commands
,anything else without these 2 ?

**Comment by ScRiPt1337** [comment]
you can run any shell command android support
