### ISSUE TITLE
Failed to push code and create a revision

### ISSUE THREAD

**Issue by Rango-dz** [ScRiPt1337/Teardroid-phprat#73]
**Describe the bug**

i followed all the setps on the readme fil
but as you can see in the screen shot it keeps failing at pusing code and creating revision

**To Reproduce**
Just follow the installation steps nothing custom

**Expected behavior**
a working panel 

**Screenshots**
https://i.imgur.com/PelOD19.png

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser:  chrome
 - Version 114.0.5735.199

**Comment by hana-ri** [comment]
I'm facing the same problem

**Comment by 3hxks** [comment]
I'm facing the same problem

**Comment by ScRiPt1337** [comment]
i am working on it

**Comment by ScRiPt1337** [comment]
it has been fix

**Comment by injuryzy** [comment]
@ScRiPt1337

**Comment by ScRiPt1337** [comment]
@injuryzy dont use the release package clone it from readme

**Comment by injuryzy** [comment]
![image](https://github.com/ScRiPt1337/Teardroid-phprat/assets/43952165/867fe6e8-2019-4d58-b699-50a44692e3c7)

sorry, I don't know if there's something wrong with my operation

**Comment by Rango-dz** [comment]
@ScRiPt1337 on windows 11 worked fine, but could't excute tasks from control panel
on kali i got the same error as above
