### ISSUE TITLE
Failed to push code and create a revision

### ISSUE THREAD

**Issue by Rango-dz** [ScRiPt1337/Teardroid-phprat#74]
Describe the bug

i followed all the setps on the readme fil
but as you can see in the screen shot it keeps failing at pusing code and creating revision

To Reproduce
Just follow the installation steps nothing custom

Expected behavior
a working panel

Screenshots
https://i.imgur.com/PelOD19.png

Desktop (please complete the following information):

OS: kali linux
Browser: chrome
Version 114.0.5735.199

**Comment by x-cod3r** [comment]
same error here!

**Comment by Shi57** [comment]
Same issue

**Comment by skif2008** [comment]
uvicorn main:app --reload
...
AssertionError: No project key defined

**Comment by luchaxi** [comment]
Push your code to Space with space push
Validating your Spacefile...

Your Spacefile looks good, proceeding with your push!

✓ Successfully started your build!
✓ Successfully pushed your Spacefile!

~ Pushing your code (24 files) & running build process...

2023/08/21 10:59:39
2023/08/21 10:59:39 Parsing Spacefile...
2023/08/21 10:59:39 Scanned micros:
2023/08/21 10:59:39 └ python-app
2023/08/21  10:59:39
2023/08/21 10:59:39 Building micro python-app...
2023/08/21 10:59:42 [python-app] error: internal error

! Failed to push code and create a revision. Please try again!

**Comment by ScRiPt1337** [comment]
the issue is from deta server its better if you host it on your own server
