### ISSUE TITLE
[python-app] error: internal error

### ISSUE THREAD

**Issue by luchaxi** [ScRiPt1337/Teardroid-phprat#75]
**Describe the bug**
space push 

**To Reproduce**
 Push your code to Space with space push
Validating your Spacefile...

Your Spacefile looks good, proceeding with your push!

✓ Successfully started your build!
✓ Successfully pushed your Spacefile!

~ Pushing your code (24 files) & running build process...

2023/08/21 10:59:39
2023/08/21 10:59:39 Parsing Spacefile...
2023/08/21 10:59:39 Scanned micros:
2023/08/21 10:59:39 └ python-app
2023/08/21 10:59:39
2023/08/21 10:59:39 Building micro python-app...
2023/08/21 10:59:42 [python-app] error: internal error

! Failed to push code and create a revision. Please try again!

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac m2 /windows 10
        java version "11.0.14" 2022-01-18 LTS
       Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
       Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.14+8-LTS-263, mixed mode)
**Additional context**

**Comment by ScRiPt1337** [comment]
the issue is from deta server its better if you host it on your own server
