### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by BotolMehedi** [ScRiPt1337/Teardroid-phprat#8]
https://user-images.githubusercontent.com/64999484/134109555-aaa297ba-8a0a-4c82-874e-37d35effb5ce.mp4

@ScRiPt1337 How to solve?

**Comment by ScRiPt1337** [comment]
wait i will make proper tutorial about to use it

**Comment by BotolMehedi** [comment]
> wait i will make proper tutorial about to use it

Okkky 😍

**Comment by ScRiPt1337** [comment]
> > wait i will make proper tutorial about to use it
> 
> Okkky 😍

It's fixed in new version please try the new version
