### ISSUE TITLE
Please download a ready-made apk and we will modify it without android studio

### ISSUE THREAD

**Issue by gowwe** [ScRiPt1337/Teardroid-phprat#9]
Please download a ready-made apk and we will modify it without android studio

**Comment by ScRiPt1337** [comment]
> Please download a ready-made apk and we will modify it without android studio

As you wish the new version of teardroid you don't need android studio anymore

**Comment by cybiz-tva** [comment]
how do we modify the output apk or how do we bind it with other apk ?
